function vd0s = driftvelocities(c, a0, b0)
mult = (2.*c.distrib.E0.*c.distrib.L.^2)./...
    (c.particle(1).*c.planet(1).*c.planet(2));
vd0cg = mult.*3.*(0.5.*sin(a0).^2 + cos(a0).^2);
vd0cf = mult.*b0.*ones(1, length(a0));
vd0 = vd0cg + vd0cf;
vd0s = struct('vd0', vd0, ...
    'vd0cg', vd0cg, ...
    'vd0cf', vd0cf ...
    );
end